
import AuthContextProvider from "@/context/AuthContext";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
export const metadata = {
  title: "Netflix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
        <Navbar/>

        {children}
        <ToastContainer/>
        </AuthContextProvider>
      </body>
    </html>
  );
}
